name: umrah_app
description: "Umrah trip booking app"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  google_fonts: ^6.2.1
  provider: ^6.1.2
  cupertino_icons: ^1.0.8
  image_picker: ^1.1.2
  supabase_flutter: ^2.15.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

dependency_overrides:
  path_provider_android: 2.2.16

flutter:
  uses-material-design: true
  generate: true
